-- V1__initial_schema.sql
-- Complete initial schema for SplitIt, derived from JPA entities.
-- Uses IF NOT EXISTS to safely adopt an existing production database.

-- ============================================================
-- users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ============================================================
-- events
-- ============================================================
CREATE TABLE IF NOT EXISTS events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    description     TEXT,
    icon_key        VARCHAR(50),
    base_currency   VARCHAR(3)      NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_events_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_events_owner_id ON events (owner_id);

-- ============================================================
-- event_members
-- ============================================================
CREATE TABLE IF NOT EXISTS event_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT          NOT NULL,
    user_id         BIGINT,
    display_name    VARCHAR(100)    NOT NULL,
    joined_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_event_members_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_event_members_user  FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT uk_event_members_event_user UNIQUE (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_event_members_event_id ON event_members (event_id);
CREATE INDEX IF NOT EXISTS idx_event_members_user_id  ON event_members (user_id);

-- ============================================================
-- expenses
-- ============================================================
CREATE TABLE IF NOT EXISTS expenses (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id            BIGINT          NOT NULL,
    paid_by_member_id   BIGINT          NOT NULL,
    name                VARCHAR(150)    NOT NULL,
    original_amount     NUMERIC(19, 4)  NOT NULL,
    original_currency   VARCHAR(3)      NOT NULL,
    exchange_rate       NUMERIC(19, 6)  NOT NULL,
    base_amount         NUMERIC(19, 4)  NOT NULL,
    expense_date        DATE            NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_expenses_event   FOREIGN KEY (event_id)          REFERENCES events (id),
    CONSTRAINT fk_expenses_paid_by FOREIGN KEY (paid_by_member_id) REFERENCES event_members (id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_event_id          ON expenses (event_id);
CREATE INDEX IF NOT EXISTS idx_expenses_paid_by_member_id ON expenses (paid_by_member_id);

-- ============================================================
-- invite_links
-- ============================================================
CREATE TABLE IF NOT EXISTS invite_links (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT          NOT NULL,
    token       VARCHAR(128)    NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invite_links_event    FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_invite_links_event_id UNIQUE (event_id),
    CONSTRAINT uk_invite_links_token    UNIQUE (token)
);
