FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY gradlew settings.gradle.kts build.gradle.kts ./
COPY gradle gradle

RUN chmod +x ./gradlew

COPY src src

RUN ./gradlew bootJar --no-daemon -x test \
    && find build/libs -type f -name "*.jar" ! -name "*-plain.jar" -exec cp {} /app/app.jar \;

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/app.jar app.jar

# En lugar de hardcodear 8080, le indicamos a Spring Boot que lea la variable $PORT que inyecta Vercel
ENTRYPOINT ["sh", "-c", "java -Dserver.port=${PORT:-8080} -jar app.jar"]